### ISSUE TITLE
Only report not OK jobs

### ISSUE THREAD

**Issue by nothing-fr** [waa/bacula#5]
Hi,

Is it possible to only reports jobs that are not OK ?

I don't see any solution to do this ?

Regards, Fred

**Comment by waa** [comment]
Hello,

Thank you for the comment. 

I had planned on adding a `jobstatus` option a long time ago, but it ended up on the back burner while I added some other more complicated and interesting things. :)

Since you made this request yesterday, I have already gone ahead and implemented this option. I am in the testing phase right now, but I should be able to push this new feature shortly. 

You will be able to choose between any combination of jobstatus available. To see the options, `SELECT * FROM status;`  (note:, not all of these are implemented in the Bacula code, but I included them all in case they ever are.)

New option will be like:
```
-x, --jobstatus <jobstatus>  Job status to report on [default: aABcCdDeEfFiIjmMpRsStT] (all job statuses)
```

**Comment by waa** [comment]
Hello Fred,

The latest version with the addition of this feature has been pushed. 

One caveat is that [R]unning and [C]reated but not yet running jobs will always be pulled into the list.

I am not sure if I will address this or just leave it as-is because it will affect so many other things.

**Comment by nothing-fr** [comment]
I think one status is missing ? (W | Job terminated normally with warnings), but everything else seems ok for me ! thank you !

**Comment by waa** [comment]
*sql
Entering SQL query mode.
Terminate each query with a semicolon.
Terminate query mode with a blank line.
Enter SQL query: select * from status;
+-----------+---------------------------------+----------+
| jobstatus | jobstatuslong                   | severity |
+-----------+---------------------------------+----------+
| C         | Created, not yet running        |       15 |
| R         | Running                         |       15 |
| B         | Blocked                         |       15 |
| T         | Completed successfully          |       10 |
| E         | Terminated with errors          |       25 |
| e         | Non-fatal error                 |       20 |
| f         | Fatal error                     |      100 |
| D         | Verify found differences        |       15 |
| A         | Canceled by user                |       90 |
| F         | Waiting for Client              |       15 |
| S         | Waiting for Storage daemon      |       15 |
| m         | Waiting for new media           |          |
| M         | Waiting for media mount         |       15 |
| s         | Waiting for storage resource    |       15 |
| j         | Waiting for job resource        |       15 |
| c         | Waiting for client resource     |       15 |
| d         | Waiting on maximum jobs         |       15 |
| t         | Waiting on start time           |       15 |
| p         | Waiting on higher priority jobs |       15 |
| a         | SD despooling attributes        |       15 |
| i         | Doing batch insert file records |       15 |
| I         | Incomplete Job                  |       25 |
+-----------+---------------------------------+----------+

**Comment by waa** [comment]
> I think one status is missing ? ([W | Job terminated normally with warnings](https://www.bacula.org/11.0.x-manuals/en/main/Job_status.html#blb:director:job:status)), but everything else seems ok for me ! thank you !

The `W` status (Backup OK -- with warnings) used to be in the 'status' table, but since it was never implemented anywhere in the code It seems like the developers finally decided to remove it from the 11.0.5 Community version status table. This would correlate to the 12.x Enterprise version.

I hadn't noticed when I did my `select * from status` sql query the other day that they had removed the `W`. It may still be in your catalog if you are using a 9.x series Community Edition. Don't worry about it missing, since no job would ever have a jobstatus = W anyway. :)

Glad it seems to be working for you.

**Comment by waa** [comment]
Hmmm, looks like I partially mis-wrote that previous comment. The 'W' jobstatus is checked for in Bacula's internal SQL queries when looking for "OK" jobs along with 'T' (and many other ones), but 'W' is never written to the db as I mentioned - this much is true.
It is also not in the status table, and looking back in all the git commits, it apparently never was, even though I was sure it was. :)
